## Working Environments

+ run all cells button in notebook
+ you can't take jupyter notebook into production
+ notebook vs scripts(sublime, atom, pycharm)



In [1]:
import os

In [2]:
os.environ['PYTHONPATH']

KeyError: 'PYTHONPATH'

In [3]:
os.environ.keys()

KeysView(environ({'CLUTTER_IM_MODULE': 'xim', 'CONDA_SHLVL': '1', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz

In [4]:
os.environ['PATH']

'/home/mathlizard/anaconda3/envs/myenv/bin:/home/mathlizard/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

In [5]:
import site

In [14]:

def hello():
    '''prints hello'''
    print('hello')

In [16]:
hello.__doc__

'prints hello'

In [18]:
site.abs_paths?

In [19]:
fp = open('junk.txt', 'w')

In [20]:
fp.close()

In [21]:
a = os.path.abspath('junk.txt')

In [22]:
a

'/home/mathlizard/tristan_class/junk.txt'

In [23]:
os.path.split(a)

('/home/mathlizard/tristan_class', 'junk.txt')

In [24]:
os.path.dirname(a)

'/home/mathlizard/tristan_class'

In [25]:
os.path.basename(a)

'junk.txt'

In [27]:
from __future__ import division

In [28]:
3/2

1.5

In [53]:
# Step 1: finding all directories with python modules
# Step 2: searching each of these for module site.py
import sys
path_list = sys.path


In [54]:
import os

In [55]:
os.curdir

'.'

In [56]:
os.curdir?

In [57]:
list(os.walk(os.curdir))

[('.', ['.ipynb_checkpoints', '.git'], ['Day1.ipynb', 'junk.txt']),
 ('./.ipynb_checkpoints', [], ['Day1-checkpoint.ipynb']),
 ('./.git',
  ['refs', 'objects', 'branches', 'hooks', 'info'],
  ['HEAD', 'description', 'index', 'config']),
 ('./.git/refs', ['tags', 'heads'], []),
 ('./.git/refs/tags', [], []),
 ('./.git/refs/heads', [], []),
 ('./.git/objects', ['2f', 'pack', 'info'], []),
 ('./.git/objects/2f', [], ['d64429bf421126b7000c94ce0f6fd186fbd01f']),
 ('./.git/objects/pack', [], []),
 ('./.git/objects/info', [], []),
 ('./.git/branches', [], []),
 ('./.git/hooks',
  [],
  ['prepare-commit-msg.sample',
   'pre-rebase.sample',
   'pre-applypatch.sample',
   'post-update.sample',
   'commit-msg.sample',
   'fsmonitor-watchman.sample',
   'update.sample',
   'pre-push.sample',
   'pre-receive.sample',
   'applypatch-msg.sample',
   'pre-commit.sample']),
 ('./.git/info', [], ['exclude'])]

In [62]:
path_list[0]

''

In [63]:
path_list

['',
 '/home/mathlizard/anaconda3/lib/python36.zip',
 '/home/mathlizard/anaconda3/lib/python3.6',
 '/home/mathlizard/anaconda3/lib/python3.6/lib-dynload',
 '/home/mathlizard/anaconda3/lib/python3.6/site-packages',
 '/home/mathlizard/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/home/mathlizard/.ipython']

In [68]:
for i in range(len(path_list)):
    for dirpath, dirnames, filenames in os.walk(path_list[i]):
        for fp in filenames:
            target = os.path.basename(fp)
            if target == 'site.py':
                print(os.path.abspath(fp))

/home/mathlizard/tristan_class/site.py


In [89]:
def find_path(basename):
    """This returns the absolute path of a module"""
    assert (type(basename) == str), 'basename must be a string'
    root = basename[len(basename)-3:]
    assert (root == '.py'), 'basename must be a python module'
    for i in range(len(path_list)):
        for dirpath, dirnames, filenames in os.walk(path_list[i]):
            for fp in filenames:
                target = os.path.basename(fp)
                if target == basename:
                    return os.path.abspath(fp)

     

In [90]:
find_path('site.py')

'/home/mathlizard/tristan_class/site.py'

In [91]:
find_path(3)

AssertionError: basename must be a string

In [93]:
find_path('junk.txt')

AssertionError: basename must be a python module

In [95]:
import numpy as np

[exercises with numpy] (https://www.w3resource.com/python-exercises/numpy/python-numpy-random.php)

Exercise #1: Write python program that generates five random numbers from the normal distribution.

In [144]:
def gaussian_numbers(n):
    array = []
    for i in range(n):
        array.append(np.random.normal())
    return array


In [145]:
gaussian_numbers(5)

[-0.9985976683997893,
 0.7072338790055284,
 0.8612296162698262,
 1.1131883983325148,
 0.835954638640718]

Exercise #2: Write a python program to generate six random numbers between 10 and 30.

In [146]:
def random_10_to_30(n):
    return [np.random.randint(10, high=30) for i in range(n)]
    

In [147]:
random_10_to_30(6)

[13, 27, 27, 15, 12, 16]

Exercise #3: Write a program to create a 3x3x3 array with random values

In [148]:
x = np.random.random((3,3,3))

In [149]:
x

array([[[0.96320103, 0.90005643, 0.48920142],
        [0.89207698, 0.65697285, 0.06455816],
        [0.74209438, 0.65105393, 0.31664622]],

       [[0.61392529, 0.07162865, 0.56015256],
        [0.98117962, 0.37665487, 0.29100624],
        [0.59030707, 0.26488112, 0.53191357]],

       [[0.05474691, 0.37255747, 0.55013146],
        [0.60367509, 0.61454917, 0.79847562],
        [0.05683059, 0.20630334, 0.43651902]]])

Exercise #4: write a program to create a 5x5 array with random values and find the minimum and maximum values.

In [150]:
def max_min(dimensions):  #dimensions should be a tuple
    y = np.random.random(dimensions)
    return y.max(), y.min()

In [151]:
max_min((5,5))

(0.954775616973367, 0.008442633488595086)

Exercise #5: Write a program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [152]:
y = np.random.random((10,4))

In [153]:
def extract_rows(n):
    return y[n[0]:n[1]: , :]

In [154]:
extract_rows((0, 4))

array([[0.55981149, 0.12230718, 0.24213114, 0.90218651],
       [0.76243488, 0.12429522, 0.88233946, 0.84172892],
       [0.74958687, 0.67669681, 0.63211084, 0.06841541],
       [0.21607635, 0.17449197, 0.37522572, 0.63167466]])

Exercise #6: Write a program to shuffle numbers between 0 and 10 (inclusive)

In [155]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks','f4')])

In [158]:
a = np.array([('liz', '27', 74),('max', '31', 48)], dtype=student)

In [159]:
a

array([(b'liz', 27, 74.), (b'max', 31, 48.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [160]:
a = np.arange(25)

In [162]:
a.ndim

1

In [163]:
b = a.reshape(5,5)

In [164]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [165]:
b.itemsize

8

In [180]:
z = np.array([1,2,19.23492,520,5], dtype=np.int8)

In [181]:
z.itemsize

1

In [182]:
z

array([ 1,  2, 19,  8,  5], dtype=int8)

In [183]:
x = np.array(np.arange(5))

In [184]:
x

array([0, 1, 2, 3, 4])

In [185]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [186]:
x = np.empty([3,2],dtype=int)

In [187]:
x

array([[4049070531863519844, 3554518993672417325],
       [3329907498654186037, 2475353828618351670],
       [7236833184642769452, 7881144752318672485]])

In [192]:
numpy.zeros((5,3,2), dtype=float, order='C')

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [193]:
numpy.zeros((5,3,2), dtype=float, order='F')

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [194]:
x=np.ones(4)

In [195]:
x

array([1., 1., 1., 1.])

In [196]:
list=range(5)

In [197]:
list

range(0, 5)

In [198]:
it=iter(list)
x = np.fromiter(it, dtype=float)

In [199]:
x

array([0., 1., 2., 3., 4.])

In [200]:
x=np.linspace(10,20,5)

In [201]:
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [204]:
y = np.linspace(10,19,5, endpoint=False)

In [205]:
y

array([10. , 11.8, 13.6, 15.4, 17.2])